apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitor
  name: grafana-config
data:
  grafana.ini: |
    [server]
    http_addr = 0.0.0.0
    http_port = 3000
    domain = example.com
  # Add other Grafana configuration options as needed

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: monitor
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/local/bin/grafana  # Replace with the actual path on your host machine

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitor
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitor
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:9.0.2
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-config-volume
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-data-volume
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-config
      - name: grafana-data-volume
        persistentVolumeClaim:
          claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: monitor
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32000
  type: NodePort

