apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitor
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: keep
            regex: https
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
      - job_name: 'node-exporter'
        static_configs:
          - targets: 
           # - 192.168.1.92:9100
           # - 192.168.1.91:9100
           # - 192.168.1.93:9100
            - 192.168.1.94:9100  
      
      - job_name: 'kube-metrics'
        static_configs:
          - targets:
            - 192.168.1.94:32080

