apiVersion: v1
kind: Service
metadata:
  namespace: monitor
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30000
